### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by iiiir** [guyduche/Blast2Bam#5]
I am able to make, but receiving seg fault error. any clue?
here are the steps:

[Blast2Bam] $ make
(cd src && make)
make[1]: Entering directory `/home/wangs92/apps/Blast2Bam/src'
xsltproc --output parseXML.c --stringparam fileType c schema2c.xsl schema.xml
xsltproc --output parseXML.h --stringparam fileType h schema2c.xsl schema.xml
gcc -c -O3 -Wall `xml2-config --cflags` -o parseXML.o parseXML.c
gcc -c -O3 -Wall `xml2-config --cflags` -o blastSam.o blastSam.c
gcc -c -O3 -Wall `xml2-config --cflags` -o printSam.o printSam.c
gcc -c -O3 -Wall `xml2-config --cflags` -o shortRead.o shortRead.c
gcc -c -O3 -Wall `xml2-config --cflags` -o utils.o utils.c
gcc -c -O3 -Wall `xml2-config --cflags` -o main.o main.c
gcc -o ../bin/blast2bam parseXML.o blastSam.o printSam.o shortRead.o utils.o main.o -lz `xml2-config --libs`
gcc -c -O3 -Wall `xml2-config --cflags` -o fastq2fasta.o fastq2fasta.c
gcc -o ../bin/fastq2fasta fastq2fasta.o shortRead.o utils.o -lz `xml2-config --libs`
make[1]: Leaving directory `/home/wangs92/apps/Blast2Bam/src'

$ ~/apps/Blast2Bam/bin/blast2bam test_blast.xml ref.dict test.fa > test.sam
Segmentation fault

$ ~/apps/Blast2Bam/bin/blast2bam test_blast.xml ref.fa test.fa > test.sam
Segmentation fault

$ ~/apps/Blast2Bam/bin/blast2bam -h
Blast2Bam. Last compilation: Sep 14 2017 at 12:46:51.

Usage: blast2bam [options] <Blast XML output> <reference sequence dictionary> <FastQ_1> [FastQ_2]

Options:
 --output         | -o FILE       Output file (default: stdout)
 --interleaved    | -p            Interleaved data
 --readGroup      | -R STR        Read group header line '@RG\tID:foo'
 --minAlignLength | -W INT        Discard alignments shorter than [INT]
 --shortCigar     | -c            Short version of the CIGAR string ('M' instead of '=' and 'X')
 --posOnChr       | -z            Adjust the alignment position to the first position of the reference
 --help           | -h            Get help (this screen)

Thanks a lot,

Shuoguo

**Comment by guyduche** [comment]
Hello Shuoguo,

The compilation part looks right to me.

Your second test was right, making a dictionary of the reference is no longer necessary. You should use the fasta file of your reference directly.

The usage shown in your third test isn't right. Did you modify the code?

Can you send me your test_blast.xml, ref.fa and test.fa so that I can have a more in-depth look at your problem?

Aurélien

**Comment by CarlijnB** [comment]
Hi Aurelien,
I'm getting the same issue - "Segmentation fault (core dumped)", with similar usage. Please advise?

#Make
~/progs/Blast2Bam-master$ make
(cd src && make)
make[1]: Entering directory '/home/s1144826/progs/Blast2Bam-master/src'
mkdir ../bin
xsltproc --output parseXML.c --stringparam fileType c schema2c.xsl schema.xml
xsltproc --output parseXML.h --stringparam fileType h schema2c.xsl schema.xml 
gcc -c -O3 -Wall `xml2-config --cflags` -o parseXML.o parseXML.c
gcc -c -O3 -Wall `xml2-config --cflags` -o blastSam.o blastSam.c
gcc -c -O3 -Wall `xml2-config --cflags` -o printSam.o printSam.c
gcc -c -O3 -Wall `xml2-config --cflags` -o shortRead.o shortRead.c
gcc -c -O3 -Wall `xml2-config --cflags` -o utils.o utils.c
gcc -c -O3 -Wall `xml2-config --cflags` -o main.o main.c
gcc -o ../bin/blast2bam parseXML.o blastSam.o printSam.o shortRead.o utils.o main.o -lz `xml2-config --libs`
gcc -c -O3 -Wall `xml2-config --cflags` -o fastq2fasta.o fastq2fasta.c
gcc -o ../bin/fastq2fasta fastq2fasta.o shortRead.o utils.o -lz `xml2-config --libs`
make[1]: Leaving directory '/home/s1144826/progs/Blast2Bam-master/src'

#Piping through from BLAST
~/progs/Blast2Bam-master$ blastn -task dc-megablast -query co2map.fasta -subject ref2map.fasta -outfmt 5 | blast2bam - ref2map.fasta co2map.fasta
Segmentation fault (core dumped)

#Creating the XML file first
~/progs/Blast2Bam-master$ blastn -task dc-megablast -query co2map.fasta -subject ref2map.fasta -outfmt 5 > test.xml
~/progs/Blast2Bam-master$ blast2bam test.xml ref2map.fasta co2map.fasta
Segmentation fault (core dumped)
