### ISSUE TITLE
silently concatenates output

### ISSUE THREAD

**Issue by aubreybailey** [guyduche/Blast2Bam#6]
if you run blast2bam twice, the output is concatenated on to the end of the first file. This is slightly unexpected, as most conventions suggest that it should overwrite the existing output.
which is to say that it >> when I think it should >
Also, this whole thing is probably rolled into https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/blast2sam/BlastToSam.java at this point, right?

**Comment by lindenb** [comment]
> Also, this whole thing is probably rolled into https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/blast2sam/BlastToSam.java

no, the C program was written later and @guyduche who was my student at this time thought about this  problem more than I did.

Furthermore, FYI there is now a SAM output for  blast https://ncbi.github.io/magicblast/doc/output.html  (never tested).

**Comment by guyduche** [comment]
Hello,

Thanks for pointing out this issue.
When I wrote this program, it never occurred to me that someone would have a need to run it twice with the same output.
It's now fixed.

@lindenb: I ran some tests with the last version of Blast (2.8.1), the SAM output is still not great. Seq and ref names are changed, paired-end data is not recognized as such, ...

Have a good day
