### ISSUE TITLE
Handling fasta with multiple sequences

### ISSUE THREAD

**Issue by leoqiang** [guyduche/Blast2Bam#7]
Does package correctly handling an reference fasta file containing multiple sequences? I always got '[W::sam_parse1] urecognized reference name; treated as unmapped' when checking the resulted BAM file with samtools.  In the header, there is only one reference. Using pysam to read the raw record, I see that the RNAME field is of value '-1' (see below).

> [W::sam_parse1] urecognized reference name; treated as unmapped
M01937:277:000000000-C69RF:1:2117:20923:11825   4       -1      49595148        60      64S19=1X11=1X2=1I17=1X1=1X6=1X12=1X7=1X14=1X2=1X2=1X8=1X1=1X7=1X10=1X2=1X5=1X2=1X8=1X14=1X6=1X1=1X2=1X5=1X2=1X5=1X21=1X1=1X9=1X6=       -1      -1      237     AGGTTCAGTTAAGTCTTCAGAAAATACAACATAAGAATGGCTTCTAAAAGGGCTCTGGTCATCCTGGCTAAAGGAGCAGAGGAGATGGAGACGGTTATTCCTGTAGATGTCATGAGACGAGCTGGAATTAAGGTCACCGTTGCAGGCCTGGCTGGAAAAGATCCGGTGCAGTGTAGTCGTGATGTTGTCATTTGTCCCGACGCCAGCCTGGAAGATGCCAAAAAAGAGGGACCTTATGACGTGGTGGTTCTGCCGGGAGGCAATCTGGGTGCACAGAATTTATCGGAGTCTGCTGCTGTGA        None    [('NM', 29), ('AS', 324), ('XB', 293.4320068359375), ('XE', '4.02e-77')]

**Comment by leoqiang** [comment]
PS: I also noticed that it seems that it does not work with blastdb generated with '-parse_seqids' option...

**Comment by leoqiang** [comment]
I just did a test with a freshedly downloaded fasta reference. It worked. However, the previous fasta file has been used with many other tools and causes no issue. The only difference is it uses this type of sequence id 'gi|407479587|ref|NC_018658.1|'.  Would this be the issue?

**Comment by leoqiang** [comment]
I finally got the issue. The fasta file I use had empty line in between each sequence record. That might cause blast2bam think the file has ended, and only retrieved the first sequence then quit pasing FASTA reference...

**Comment by guyduche** [comment]
Hi,
I'm glad you found a solution to your problem.
I pushed a fix for this issue.
It should now work as well with your previous fasta file.
