### ISSUE TITLE
blast2bam program missing 

### ISSUE THREAD

**Issue by tushar-ahmed** [guyduche/Blast2Bam#8]
(cd src && make)
make[1]: Entering directory '/home/d3w/Blast2Bam/src'
xsltproc --output parseXML.c --stringparam fileType c schema2c.xsl schema.xml
xsltproc --output parseXML.h --stringparam fileType h schema2c.xsl schema.xml 
gcc -c -O3 -Wall `xml2-config --cflags` -o parseXML.o parseXML.c
gcc -c -O3 -Wall `xml2-config --cflags` -o blastSam.o blastSam.c
gcc -c -O3 -Wall `xml2-config --cflags` -o printSam.o printSam.c
gcc -c -O3 -Wall `xml2-config --cflags` -o shortRead.o shortRead.c
gcc -c -O3 -Wall `xml2-config --cflags` -o utils.o utils.c
gcc -c -O3 -Wall `xml2-config --cflags` -o main.o main.c
gcc -o ../bin/blast2bam parseXML.o blastSam.o printSam.o shortRead.o utils.o main.o -lz `xml2-config --libs`
gcc -c -O3 -Wall `xml2-config --cflags` -o fastq2fasta.o fastq2fasta.c
gcc -o ../bin/fastq2fasta fastq2fasta.o shortRead.o utils.o -lz `xml2-config --libs`
make[1]: Leaving directory '/home/d3w/Blast2Bam/src'

this is the message after compilation but I'm not getting blast2bam program, rather it provides blast2sam.pl program. 
help please

**Comment by guyduche** [comment]
Hello,
The compilation message looks alright.
blast2bam should be in your '/home/d3w/Blast2Bam/bin' folder.
blast2sam.pl is part of Samtools. It showed up because Samtools had probably been added to your PATH.
If you want blast2bam to do the same, you can add '/home/d3w/Blast2Bam/bin' to your PATH.
